### ISSUE TITLE
[Bug] Invalid slug cause the API to return 500 internal server error

### ISSUE THREAD

**Issue by Miminiverse** [dev-launchers/strapiv4#102]
**Describe the bug**
The request to http://localhost:1337/api/projects/:id returns 500 internal server error

**To Reproduce**
1. Change the env to test
2. Send a request to http://localhost:1337/api/projects/1

**Expected behavior**
The API returns 500 internal server error

**Environment**
Test

**Comment by chungthuang** [comment]
Fixed in #105
