### ISSUE TITLE
[Bug] calling /api/users/{id} is returning 204 with no clear reason in staging

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/strapiv4#151]
**Describe the bug**
I can't seem to get a specific user from `/api/users/{id}` endpoint in staging, this issue only happens there.
Strapi in dev mode works fine and returns the user as expected!

**To Reproduce**
1. Make a GET request to `/api/users/{id}`
2. wait
3. get status code of 204 with no clear reason why the request was rejected

**Expected behavior**
The requested user being returned by the their `id`

**Screenshots**
```
❯ curl -X 'GET' \
  'https://apiv4-staging.devlaunchers.org/api/users/8' \
  -H 'accept: application/json' \
  -I           
HTTP/2 204 
date: Thu, 22 Feb 2024 03:12:32 GMT
content-security-policy: connect-src 'self' https:;img-src 'self' data: blob: dl.airtable.com https://market-assets.strapi.io https://devlaunchersstaging.blob.core.windows.net;media-src 'self' data: blob: dl.airtable.com https://devlaunchersstaging.blob.core.windows.net;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
referrer-policy: no-referrer
strict-transport-security: max-age=31536000; includeSubDomains
vary: Origin
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-envoy-upstream-service-time: 83
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: Strapi <strapi.io>
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=gjCCbVVAmEB3rDvGK%2Fp19otCCOuJZRNJyovm%2FRhpCq51fP%2FQ1%2BqIy0XhmlKCqlaQiDq7kqOjZHDAHfbGaNGXuaov9PkR%2BIlBR%2BFxFTYFyNEZFZYD5AM1G8OOuqL6wWMAsNO5tPoLqKa3Mf%2BRByZaTTnCKvLrL1DTRkdwKTY%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 85940c4addd6bae8-MXP
alt-svc: h3=":443"; ma=86400
```

**Environment**
happens whether being called in a browser or from curl

**Additional context**
[HAR file](https://cdn.discordapp.com/attachments/633976948103577602/1210062751678861382/apiv4.devlaunchers.org_Archive_24-02-22_06-15-07.har?ex=65e931c1&is=65d6bcc1&hm=e1f3e6dbdba405452fdb2eb5c1011fe9e66809f03c654de125f5ec6c08ff3aab&) for inspecting my request in the browser

**Comment by tiagopazhs** [comment]
Reading this issue, I planned to do this tests:
- Reproduce same scenario in development to garantee that it is working. Reproduce same scenario in staging to garantee that it is NOT working.
- Check if id 8 is a valid Id.
- Try to find an id that exists in staging.
- Try same request using curl (at first figure out how to authenticate using curl requests)
- Try same using HTTP requsts using Portman (authenticated and public req)
- Check the diferrences of permisions in staging and development (focus in this related to user)
-

**Comment by tiagopazhs** [comment]
Reading this issue, I planned to do this tests:
- Reproduce same scenario in development to garantee that it is working. Reproduce same scenario in staging to garantee that it is NOT working.
- Check if id 8 is a valid Id.
- Try to find an id that exists in staging.
- Try same request using curl (at first figure out how to authenticate using curl requests)
- Try same using HTTP requsts using Portman (authenticated and public req)
- Check the diferrences of permisions in staging and development (focus in this related to user)
-

**Comment by tiagopazhs** [comment]
As discussed during the platform meeting, we realize this issue is a bit old, and maybe we can not reproduce this in the current version.
Important point to use to validate user/{id} route.
- Necessary to checkout to Wolfgang open PR that have some new rules regarding authentication and rebase from master branch. 
- The expected is that an authenticated user should be able to get some public information from other users like profile picture and name, but not have access to private information like email.
- To simulate an authenticated user in staging, necessary to authenticate and then get the authentication token from Cookies.

**Comment by tiagopazhs** [comment]
Follow bellow the tests of the route /users/{id} local:


## Main branch: origin/main
- get current user: users/{current user id}
```
{
    "id": 3,
    "username": "testNormalUser",
    "email": "test_normal_user@teste.com",
    "provider": "local",
    "confirmed": true,
    "blocked": false,
    "discordUsername": null,
    "userId": null,
    "hasAcceptedTermsOfService": null,
    "hasSubscribedEmails": null,
    "discord_avatar": null,
    "discord_discriminator": null,
    "job": "other",
    "experience": null,
    "schedule": null,
    "completedOnboarding": false,
    "createdAt": "2024-09-08T13:07:20.714Z",
    "updatedAt": "2024-09-08T13:07:33.166Z"
}
```

- get other users: users/{other user id}
```
{
    "id": 1,
    "username": "tester",
    "email": "tester@test.com",
    "provider": "local",
    "confirmed": true,
    "blocked": null,
    "discordUsername": null,
    "userId": null,
    "hasAcceptedTermsOfService": null,
    "hasSubscribedEmails": null,
    "discord_avatar": null,
    "discord_discriminator": null,
    "job": "other",
    "experience": null,
    "schedule": null,
    "completedOnboarding": false,
    "createdAt": "2024-08-08T23:59:40.294Z",
    "updatedAt": "2024-08-08T23:59:40.443Z"
}
```

- get user without authenticate: users/{random user id}
```
{
    "data": null,
    "error": {
        "status": 403,
        "name": "ForbiddenError",
        "message": "You are not allowed to perform the following actions: plugin::users-permissions.user.findOne",
        "details": {
            "dissallowedScopes": [
                "plugin::users-permissions.user.findOne"
            ]
        }
    }
}
```
## Wolfgan branch: becevka/179-disable-user-details

- get current user: users/{current user id}
```
{
    "id": 3,
    "username": "testNormalUser",
    "email": "test_normal_user@teste.com",
    "provider": "local",
    "confirmed": true,
    "blocked": false,
    "discordUsername": null,
    "userId": null,
    "hasAcceptedTermsOfService": null,
    "hasSubscribedEmails": null,
    "discord_avatar": null,
    "discord_discriminator": null,
    "job": "other",
    "experience": null,
    "schedule": null,
    "completedOnboarding": false,
    "createdAt": "2024-09-08T13:07:20.714Z",
    "updatedAt": "2024-09-08T13:07:33.166Z"
}
```


- get other users: users/{other user id}
```
{
    "id": 2,
    "username": "tester2"
}
```

- get user withouy authenticate: users/{random user id}
```
{
    "data": null,
    "error": {
        "status": 403,
        "name": "ForbiddenError",
        "message": "You are not allowed to perform the following actions: plugin::users-permissions.user.findOne",
        "details": {
            "dissallowedScopes": [
                "plugin::users-permissions.user.findOne"
            ]
        }
    }
}
```

**Comment by tiagopazhs** [comment]
Summary:

- Wolfgan branch is limiting access to only public fields (id and user name).
- Question: Is it correct to display only id and username? Is there another information that will need to be displayed as public information like profile picture ?

**Comment by tiagopazhs** [comment]
As dicussed during Todays Platform meeting, we are not able to reproduce it. So we will close that.
