### ISSUE TITLE
[Bug] Frontend can misattribute authors of collections in strapi

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/strapiv4#158]
**Describe the bug**
Currently the frontend can send requests to backend with "author" being a field in the request body and that field usually expects a number that refers to the id in the user collection.

This is a really bad way to handle ownership of content as anyone who knows a little bit about reverse engineering can maliciously use those endpoints and submit comments, ideas, etc while misattributing them to another user by altering the POST request body to include a different user.id than their's.

**To Reproduce**
1. Login in https://staging.devlaunchers.org
2. Navigate to https://staging.devlaunchers.org/ideaspace/workshop/254 or any other idea workshop
3. Submit a comment
4. Observe the request you made in network devtools
5. Mimic the request but with changing the payload to include a different "author" id
6. Successfully misattributed the comment to someone else

**Expected behavior**
"authorId" should point to the users-permissions.user id and should be inferred in strapiv4 based on the cookie "token" being supplied with the request and ONLY give authorship based on the currenly logged-in user token.

**Non-Functional Requirement**
Existing comments data should be migrated to fill the new "authorId" field based on current comment's author. 
Suggested to find a user by name and update authorId. After that, we can remove "author" field.

**Screenshots**
![image](https://github.com/dev-launchers/strapiv4/assets/27841994/3514b68c-724c-4b08-885b-ffed0c064d16)

**Comment by Enjoy2Live** [comment]
Looks like @oriyomibadmus has handled this case when a creating an idea-card in
https://github.com/dev-launchers/strapiv4/blob/main/src/api/idea-card/content-types/idea-card/lifecycles.js

Which defeats the propose of having the "author" and "idea-owner" field being required from the frontend.

also there are other unprotected endpoints like comment so we need to attach it to lifecycle hook like we did with idea-card

**Comment by becevka** [comment]
Basically we will need to:

Add the field that point to user.
Since, we have some comments already created in production, and we want to make sure the userIds are correctly filled in for those comment. So, we will need to migrate existing author field to a new field.
Also, we need to add logic on the backend side to make sure the authorId is set upon comment creation based on the currently logged-in user and is not modifiable upon update.

**Comment by becevka** [comment]
Few more updates after discussion with IdeaTeam.
- we want to support backward compatibility both on data and behavior
- for data compatibility, we need to migrate data from author field to `authorId` using a script
- for behavior compatibility, we need to make sure `author` field continue to be populated with user name.
@zar92 @oriyomibadmus
