### ISSUE TITLE
Track how long a user has been on a team

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#18]
Add a collection to track when a user joins and leaves a team. When a user is added to a team, insert an entry to this collection. Then set the leave time when a user is removed from a team.

**Comment by oriyomibadmus** [comment]
![Screenshot 2023-08-07 at 3.19.08 PM.png](https://images.zenhubusercontent.com/635016a780558193d89c6eb2/e0a465b1-fe42-48d2-97f2-6a12267ff84e)!
[Screenshot 2023-08-07 at 3.19.41 PM.png](https://images.zenhubusercontent.com/635016a780558193d89c6eb2/4be2d7d0-804d-4f1a-b9ab-c1e5df9ba9f3)![Screenshot 2023-08-07 at 3.20.05 PM.png](https://images.zenhubusercontent.com/635016a780558193d89c6eb2/f9956fff-46b4-4b04-833d-db0c0c701418)![Screenshot 2023-08-07 at 3.22.59 PM.png](https://images.zenhubusercontent.com/635016a780558193d89c6eb2/4b764a60-90dd-4239-bc77-a61f12f04933)!

**Comment by chungthuang** [comment]
Done in PR #80
