### ISSUE TITLE
[Platform] [Deprecation Report]  As a developer responsible for maintaining a monorepo with multiple apps I want to automatically generate a comment within a PR that lists imported deprecated features

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/strapiv4#201]
## User Story
As a developer responsible for maintaining a monorepo with multiple apps
I want to automatically generate a comment within a PR that lists imported deprecated features annotated with jsdocs
So that I can quickly identify and address potential issues within the PR

## Acceptance Criteria
- [ ] When a PR is opened or updated, a comment is automatically created.
- [ ] The comment lists all deprecated features imported from specified packages within the PR.
The comment includes the following information for each deprecated feature:
- [ ] Feature name
- [ ] Deprecation reason (if available)
- [ ] Suggested replacement (if available)
- [ ] The comment is formatted in a clear and concise manner.
- [x] The tool can be configured to include or exclude specific packages.
- [ ] The tool can be configured to trigger the comment generation based on specific PR labels or reviewers (preferable).
- [ ] The tool provides options to customize the comment's content and formatting (preferable).
- [ ] The tool integrates seamlessly with the existing PR workflow and doesn't interfere with other PR actions.

**Comment by Enjoy2Live** [comment]
@chungthuang suggested `eslint-plugin-deprecation` , I reckon we can use it in our `packages/eslint-config-bases` package and make CI job that triggers on PR.

**Comment by dbradham** [comment]
@Enjoy2Live is there anyone on the team other than yourself who could take this on?

**Comment by Enjoy2Live** [comment]
Nanda was working on it but had to step down so I took over. There's an open PR for this rn

**Comment by Enjoy2Live** [comment]
#1980
