### ISSUE TITLE
[FEAT] Package and publish types for frontend to use

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#204]
**Summary**
Having backend types in the frontend will improve integration.

**Describe the solution you'd like**
Package and publish the generated types in https://github.com/dev-launchers/strapiv4/tree/main/types/generated as a npm package. This can be a GitHub action that publishes every time there is a change in types/generated folder.

**Describe alternatives you've considered**
Merge the frontend and backend repos. But that goes against our direction to decouple teams and reduce merge conflict in the frontend.

**Acceptance criteria**
The frontend can import backend types from a npm package.

**Additional context**
 In the long-term we can consider exporting a client for frontend to call the backend.

**Comment by dbradham** [comment]
@VictorDiniz89 sorry we missed you in the team sync today. Are you able to test this feature in the staging environment, or else can you explain how someone else would?

**Comment by dbradham** [comment]
To test, we can run the same action as GitHub actions from a local machine. (with the same credentials)
