### ISSUE TITLE
Send reminders for periodic events to Discord

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#34]
For periodic events like weekly meetings or time to post status updates, we would like to get notifications in Discord. For example, 10 minutes before the backend meeting time, I would like to ping everyone with the `@Backend Project Team` role.

**Comment by VictorDiniz89** [comment]
Make integration betewen Google calendar em discord by Zapier

1- Open your gmail account go on google calendar using this url: https://console.cloud.google.com/
go on your dashboard: -> APIs & Services -> Credentials -> Create Credentials -> OAuth client ID -> Web application -> Name(use the name you desire) -> CREATE 
(DONE) your API key was created and actived

2- Create your onw Zapier accont url:https://zapier.com/app/zaps
a) In the main screen go on +Create Zap: -> Trigger: search for: Google Calendar -> Event(required) select for: Event Start -> continue (DONE)

b) Trigger: -> calendar(your gmail account) -> time Before(select your time) -> search term(select a specific word like: "MEETINGS") -> CONTINUE (DONE) -> TEST TRIGGER -> CONTINUE

c) Action: -> search for: -> Discord -> Event(Send channel Message) -> CONTINUE
Choose an Account(your discord Server) -> CONTINUE
Channel(your discord channel) -> Message Text(TYPE: Event Starting: Select: Summary -> Event Begins(Pretty) -> Description) -> Ping Username: True -> Bot Name(give your bot name) CONTINUE
TEST ACTION (DONE)
Now whe you add events on your google calendar, the Bot gonna send a message on your discord
