### ISSUE TITLE
Cannot reset password with admin endpoint

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#51]
When I clicked `Forgot your password?` in https://apiv4.devlaunchers.org/admin, I never received an email.

DB EDIT-9/22/2024:

- This seems to be happening because there is no mail provider
- The acceptance criteria for this ticket is to send a reset password email using an integrated mail provider

**Comment by becevka** [comment]
@chungthuang @zar92 
Strapi does not provide mailer by default we need to setup some SMTP provider, as simple sendmail will not really work with K8 and docker and often caught in Spam.
Here are some details https://antonioufano.com/articles/easily-send-emails-in-strapi-with-any-provider/
We can choose Brevo or SendPulse free tiers. 
https://www.brevo.com/pricing/ or https://sendpulse.com/prices/smtp

@zar92 also wonder what is the plan for email notifications support?

**Comment by dbradham** [comment]
@chungthuang this seems like it will be resolved once we set up an SMTP provider. What do you think of changing this ticket's scope to adding an SMTP provider?

**Comment by dbradham** [comment]
Still pending research on node mailer

**Comment by tiagopazhs** [comment]
Hey @dbradham ,

Just a qicly follow up.

I added the "@strapi/provider-email-nodemailer" npm áckage as you suggested.
And also added the config/plugins.js setup guided by https://www.npmjs.com/package/@strapi/provider-email-nodemailer.

I used your login credentials but I didn't have success yet.

My first try using the admin Ui I realized the logs as bellow:

```
[2024-09-28 18:24:16.307] http: POST /admin/forgot-password (31 ms) 204
[2024-09-28 18:25:18.820] info: File changed: /Users/tiagohy/md/dev-lauchers/strapiv4-dev-lauchers-api/package-lock.json
The server is restarting

[2024-09-28 18:25:22.348] info: @strapi/plugin-sentry is disabled because no Sentry DSN was provided
[2024-09-28 18:25:22.361] warn: Users-permissions registration has defaulted to accepting the following additional user fields during registration: projects,interests,idea_cards,profile,discordId,googleId,discordUsername,userId,birthday,country,zipCode,hasAcceptedTermsOfService,hasSubscribedEmails,discord_avatar,discord_discriminator,job,experience,schedule,completedOnboarding,ownedCards,comments,subscriptions
(node:28092) Warning: Missing transfer.token.salt: Data transfer features have been disabled.
Please set transfer.token.salt in config/admin.js (ex: you can generate one using Node with `crypto.randomBytes(16).toString('base64')`)
For security reasons, prefer storing the secret in an environment variable and read it in config/admin.js. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.
(Use `node --trace-warnings ...` to show where the warning was created)
`

Later I will try to add a fake route just to test if it is working.

**Comment by dbradham** [comment]
We were able to get the Strapi instance running on Tiago's machine to send an email:
![Image](https://github.com/user-attachments/assets/ba88eb77-1e5e-45d0-a769-af0737ea3a2d)

**Comment by dbradham** [comment]
@tiagopazhs @chungthuang are either of you familiar with the configuration for the reset password email template? 

![Image](https://github.com/user-attachments/assets/3a202395-dfaf-49a3-9728-ab6758bdecc7)

![Image](https://github.com/user-attachments/assets/b10ea9c6-4022-4f3e-9507-8679b2a82489)

![Image](https://github.com/user-attachments/assets/8d0c052a-2068-44a5-8daa-9e65996974d5)

**Comment by tiagopazhs** [comment]
No, I am not.

**Comment by dbradham** [comment]
@tiagopazhs next steps should be to:

1. Ensure you can still send an email from Strapi on your local instance
2. Remove all of the dynamic content from the email template in the Strapi admin UI
3. Click reset password and fill in your email

Please post the results of the test here.

**Comment by tiagopazhs** [comment]
Hello @chungthuang and @dbradham ,
I was testing the forgot password email in staging and it is working as expected:

Using the link: https://apiv4-staging.devlaunchers.org/admin/auth/forgot-password I got the following email:

![image](https://github.com/user-attachments/assets/40b5d539-02ab-4259-b960-0d3b6b14f9da)

**Comment by dbradham** [comment]
We can add new documentation for the environment variables here-https://github.com/dev-launchers/dev-launchers-platform/wiki
